#!/usr/bin/env bash
# IVKO Schoolbel installer
# Tested on Raspberry Pi OS (Debian)

set -euo pipefail

APP_USER="${SUDO_USER:-pi}"
APP_HOME="$(eval echo "~${APP_USER}")"
APP_DIR="${APP_HOME}/schoolbell"

CONFIG_DIR="/etc/schoolbell"
LOG_DIR="/var/log/schoolbell"

GUNICORN_BIND="127.0.0.1:5000"
GUNICORN_WORKERS="2"
GUNICORN_THREADS="4"
GUNICORN_TIMEOUT="30"
GUNICORN_MAX_REQUESTS="1000"
GUNICORN_MAX_REQUESTS_JITTER="100"

echo "== IVKO Schoolbel installer =="
echo "User: ${APP_USER}"
echo "App dir: ${APP_DIR}"

if [[ ! -d "${APP_DIR}" ]]; then
  echo "ERROR: expected repo at ${APP_DIR}."
  echo "Clone the repo there, or adjust APP_DIR in this script."
  exit 1
fi

if [[ ! -f "${APP_DIR}/requirements.txt" ]]; then
  echo "ERROR: requirements.txt missing in ${APP_DIR}."
  exit 1
fi

echo "== 1) System packages =="
apt-get update
# libasound2 is the runtime package pygame links against. Previously this
# was libasound2-dev (header files); those are only needed to compile
# something that wants to link against it, not to run.
apt-get install -y \
  nginx \
  python3 python3-venv python3-pip \
  logrotate \
  ffmpeg \
  alsa-utils \
  libasound2

echo "== 1b) OS timezone =="
# The schoolbell runs on local time. The application no longer carries
# its own timezone setting (was unused and confusing as a second source
# of truth) — the OS timezone is authoritative. Set it explicitly here
# so a freshly imaged Pi (often UTC by default) doesn't ring at the
# wrong moment. Idempotent: setting the same tz twice is a no-op.
TARGET_TZ="${SCHOOLBELL_TZ:-Europe/Amsterdam}"
if command -v timedatectl >/dev/null 2>&1; then
  CURRENT_TZ="$(timedatectl show --property=Timezone --value 2>/dev/null || echo '')"
  if [[ "${CURRENT_TZ}" != "${TARGET_TZ}" ]]; then
    timedatectl set-timezone "${TARGET_TZ}"
    echo "OS timezone set to ${TARGET_TZ} (was: ${CURRENT_TZ:-unknown})"
  else
    echo "OS timezone already ${TARGET_TZ}"
  fi
else
  echo "WARN: timedatectl not available, skipping OS timezone step."
fi

echo "== 2) Python venv + deps (requirements.txt) =="
cd "${APP_DIR}"
if [[ ! -d venv ]]; then
  sudo -u "${APP_USER}" python3 -m venv venv
fi

sudo -u "${APP_USER}" bash -lc "
  ${APP_DIR}/venv/bin/pip install --upgrade pip &&
  ${APP_DIR}/venv/bin/pip install -r ${APP_DIR}/requirements.txt
"

echo "== 3) Directories + permissions =="
mkdir -p "${CONFIG_DIR}" "${LOG_DIR}"
mkdir -p "${APP_DIR}/data" "${APP_DIR}/static/geluiden"
chown -R "${APP_USER}:${APP_USER}" "${APP_DIR}/data" "${APP_DIR}/static/geluiden" "${LOG_DIR}"

# ${CONFIG_DIR} must be group-writable by ${APP_USER}. Reason:
# settings_store.save() writes atomically via a tmp file that is first
# created in this directory and then renamed over config.json. If the
# directory is root:root 755 (Linux default) the webinterface (running
# as ${APP_USER}) can't create a tmp file → PermissionError.
# setgid (2775 = rwxrwsr-x) also makes new files in this directory
# automatically inherit group=${APP_USER}, so both web and daemon keep
# access without having to tune the umask.
chown root:"${APP_USER}" "${CONFIG_DIR}"
chmod 2775 "${CONFIG_DIR}"

echo "== 4) Create default config if missing =="
if [[ ! -f "${CONFIG_DIR}/config.json" ]]; then
  cat > "${CONFIG_DIR}/config.json" <<'JSON'
{
  "volume_percent": 70,
  "max_file_size_mb": 15,
  "poll_interval_sec": 2,
  "allowed_extensions": [".mp3", ".wav", ".ogg"]
}
JSON
  chmod 640 "${CONFIG_DIR}/config.json"
  chown root:"${APP_USER}" "${CONFIG_DIR}/config.json"
  echo "Created ${CONFIG_DIR}/config.json"
else
  echo "Exists: ${CONFIG_DIR}/config.json"
fi

echo "== 4b) Generate env files (credentials + session secret) if missing =="
WEB_ENV="${CONFIG_DIR}/web.env"
DAEMON_ENV="${CONFIG_DIR}/daemon.env"

if [[ ! -f "${WEB_ENV}" && ! -f "${DAEMON_ENV}" ]]; then
  ADMIN_USER="admin"
  # Use Python for password generation instead of `tr | head`, to avoid
  # SIGPIPE under `set -o pipefail`. Also cryptographically correct via secrets.
  ADMIN_PASS="$("${APP_DIR}/venv/bin/python" -c \
    'import secrets, string; print("".join(secrets.choice(string.ascii_letters + string.digits) for _ in range(16)))')"
  ADMIN_HASH="$(printf '%s' "${ADMIN_PASS}" \
    | "${APP_DIR}/venv/bin/python" -c \
      'import sys; from werkzeug.security import generate_password_hash; print(generate_password_hash(sys.stdin.read()))')"
  SECRET="$("${APP_DIR}/venv/bin/python" -c 'import secrets; print(secrets.token_hex(32))')"

  umask 077
  cat > "${WEB_ENV}" <<EOF
# Generated by install.sh — do not commit.
SCHOOLBELL_WEB_USER=${ADMIN_USER}
SCHOOLBELL_WEB_PWHASH=${ADMIN_HASH}
SCHOOLBELL_SECRET=${SECRET}

# This install runs Nginx on HTTP (port 80). Session cookies must
# therefore not have the Secure flag, otherwise the browser won't send
# them back. Set to 1 once you have HTTPS configured in Nginx.
SCHOOLBELL_SECURE_COOKIES=0
EOF
  cat > "${DAEMON_ENV}" <<EOF
# Generated by install.sh — do not commit.
SCHOOLBELL_WEB_USER=${ADMIN_USER}
SCHOOLBELL_WEB_PASS=${ADMIN_PASS}
EOF
  umask 022

  chown root:"${APP_USER}" "${WEB_ENV}" "${DAEMON_ENV}"
  chmod 640 "${WEB_ENV}" "${DAEMON_ENV}"

  echo ""
  echo "=============================================================="
  echo "  Admin login generated. NOTE NOW (will not be repeated):"
  echo ""
  echo "    User:        ${ADMIN_USER}"
  echo "    Password:    ${ADMIN_PASS}"
  echo ""
  echo "  Change by editing ${WEB_ENV} and ${DAEMON_ENV}."
  echo "=============================================================="
  echo ""
elif [[ -f "${WEB_ENV}" && -f "${DAEMON_ENV}" ]]; then
  echo "Env files already exist, skipped: ${WEB_ENV}, ${DAEMON_ENV}"
else
  echo "ERROR: only one of ${WEB_ENV} / ${DAEMON_ENV} exists."
  echo "Remove both and re-run, or edit manually."
  exit 1
fi

echo "== 5) systemd units =="
cat > /etc/systemd/system/schoolbell-web.service <<EOF
[Unit]
Description=Schoolbell Web (Gunicorn behind Nginx)
After=network.target

[Service]
User=${APP_USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${WEB_ENV}
Environment="SCHOOLBELL_CONFIG=${CONFIG_DIR}/config.json"
ExecStart=${APP_DIR}/venv/bin/gunicorn \
  --workers ${GUNICORN_WORKERS} \
  --threads ${GUNICORN_THREADS} \
  --timeout ${GUNICORN_TIMEOUT} \
  --max-requests ${GUNICORN_MAX_REQUESTS} \
  --max-requests-jitter ${GUNICORN_MAX_REQUESTS_JITTER} \
  --bind ${GUNICORN_BIND} \
  webinterface:app
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/schoolbell-daemon.service <<EOF
[Unit]
Description=Schoolbell Daemon
After=network.target schoolbell-web.service

[Service]
User=${APP_USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${DAEMON_ENV}
Environment="SCHOOLBELL_CONFIG=${CONFIG_DIR}/config.json"
Environment="API_BASE=http://127.0.0.1:5000"
ExecStart=${APP_DIR}/venv/bin/python ${APP_DIR}/schoolbelldaemon.py
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

echo "== 6) Nginx config =="
cat > /etc/nginx/sites-available/schoolbell <<'NGINX'
server {
    listen 80 default_server;
    server_name _;

    # Later: add HTTPS (self-signed or Let's Encrypt) and 80->443 redirect.

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/schoolbell /etc/nginx/sites-enabled/schoolbell
rm -f /etc/nginx/sites-enabled/default || true

nginx -t
systemctl restart nginx

echo "== 7) logrotate for events.jsonl =="
cat > /etc/logrotate.d/schoolbell-events <<EOF
${APP_DIR}/data/events.jsonl {
  daily
  rotate 14
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
}
EOF

echo "== 8) Enable + (re)start services =="
# `enable` makes the services start at boot. Separate `restart` instead
# of `--now` so that on a re-run new code, env files and unit-file
# changes are actually picked up. Restart on a non-running service just
# works (systemd treats it as a start).
systemctl enable schoolbell-web.service schoolbell-daemon.service
systemctl restart schoolbell-web.service schoolbell-daemon.service

echo "== DONE =="
echo "Open: http://<pi-ip>/"
echo
echo "Status:"
systemctl --no-pager --full status schoolbell-web.service || true
systemctl --no-pager --full status schoolbell-daemon.service || true
echo "Re-run safe: yes"
echo "To uninstall: stop + disable services, remove files + dirs created by this script."
echo "The webinterface runs on Flask 3.x via Gunicorn; running the Flask dev server manually is not supported."
echo
echo "Tip: verify audio output independently of the daemon with:"
echo "     ${APP_DIR}/venv/bin/python ${APP_DIR}/tools/belltest.py <path-to-audio-file>"
